### ISSUE TITLE
Numpy版本不兼容

### ISSUE THREAD

**Issue by chenjzhi** [vortezwohl/Bhakti#2]
使用NumPy 1编译的模块。无法运行
NumPy 2.1.1，因为它可能崩溃。
在NumPy版本中，模块必须使用NumPy 2.0进行编译。
如果您是该模块的用户，最简单的解决方案是
降级到'numpy<2'或尝试升级受影响的模块。

**Comment by vortezwohl** [comment]
在最新版本中已经解决[0.2.17](https://github.com/vortezwohl/Bhakti/compare/0.2.16...0.2.17)
